import { type CampaignLevel, type CampaignWorld, type CampaignEnemyType } from './campaignData';

// Agent mode enemy types mapped to classic enemy type system
export type AgentEnemyType = 'street_thug' | 'hired_gun' | 'cyber_hacker' | 'drone_sentry' | 'rogue_agent' | 'bodyguard' | 'operative' | 'enforcer' | 'the_broker' | 'the_architect' | 'the_double_agent' | 'the_director' | 'the_warden' | 'the_commander' | 'the_phantom' | 'the_overseer' | 'vault_sentinel' | 'vault_drone' | 'the_vault_keeper' | 'shadow_operative' | 'shadow_drone' | 'the_shadow_broker' | 'frost_trooper' | 'ice_drone' | 'the_frostbite' | 'maze_runner' | 'tunnel_rat' | 'the_minotaur' | 'lab_guard' | 'bio_drone' | 'the_catalyst' | 'omega_soldier' | 'omega_elite' | 'the_omega';

export const agentToClassicEnemyMap: Record<AgentEnemyType, CampaignEnemyType> = {
  street_thug: 'minion',
  hired_gun: 'guard',
  cyber_hacker: 'elite',
  drone_sentry: 'minion',
  rogue_agent: 'guard',
  bodyguard: 'elite',
  operative: 'guard',
  enforcer: 'elite',
  the_broker: 'boss',
  the_architect: 'boss',
  the_double_agent: 'boss',
  the_director: 'boss',
  the_warden: 'boss',
  the_commander: 'boss',
  the_phantom: 'boss',
  the_overseer: 'boss',
  vault_sentinel: 'guard',
  vault_drone: 'minion',
  the_vault_keeper: 'boss',
  shadow_operative: 'guard',
  shadow_drone: 'minion',
  the_shadow_broker: 'boss',
  frost_trooper: 'guard',
  ice_drone: 'minion',
  the_frostbite: 'boss',
  maze_runner: 'guard',
  tunnel_rat: 'minion',
  the_minotaur: 'boss',
  lab_guard: 'guard',
  bio_drone: 'minion',
  the_catalyst: 'boss',
  omega_soldier: 'guard',
  omega_elite: 'elite',
  the_omega: 'boss',
};

// Stories are sorted by grade at export time. Index ranges per grade:
// Grade 6: 0-11 (12 stories)
// Grade 7: 12-23 (12 stories)
// Grade 8: 24-34 (11 stories)
// Grade 9: 35-67 (33 stories)
// Grade 10: 68-110 (43 stories)
// Grade 11: 111-123 (13 stories)
// Grade 12: 124-169 (46 stories)

export const agentCampaignWorlds: CampaignWorld[] = [
  // TUTORIAL
  {
    id: 0,
    name: 'Training Facility',
    description: 'Complete your field training before deployment.',
    gradient: 'from-slate-400 via-zinc-500 to-gray-600',
    bgColor: 'bg-slate-900/20',
    enemyTypes: ['minion'],
    requiredGradeLevel: 0,
    storyCount: 1,
    unlockRequirement: 0,
    lore: 'Welcome, recruit. Before you enter the field, you must demonstrate your skills. Read the briefings, complete the exercises, and prove you have what it takes to become an agent.',
    levels: [
      { id: 1, storyIndex: -1, enemies: ['minion'], isBossLevel: false, starThresholds: [30, 50, 70] },
    ],
  },
  // WORLD 1 - The Underground (Grade 6, first 6: indices 0-5)
  {
    id: 1,
    name: 'The Underground',
    description: 'Infiltrate a criminal network operating beneath the city.',
    gradient: 'from-zinc-600 via-stone-700 to-neutral-800',
    bgColor: 'bg-zinc-900/20',
    enemyTypes: ['minion', 'guard'],
    requiredGradeLevel: 6,
    storyCount: 6,
    unlockRequirement: 0,
    lore: 'Intelligence reports indicate a shadowy criminal network called The Syndicate is operating from the city\'s underground tunnels. Your mission: infiltrate their ranks, gather intel, and take down their local boss — The Broker.',
    levels: [
      { id: 1, storyIndex: 0, enemies: ['minion'], isBossLevel: false, starThresholds: [60, 80, 95] },
      { id: 2, storyIndex: 1, enemies: ['minion', 'minion'], isBossLevel: false, starThresholds: [60, 80, 95] },
      { id: 3, storyIndex: 2, enemies: ['guard'], isBossLevel: false, starThresholds: [60, 80, 95] },
      { id: 4, storyIndex: 3, enemies: ['guard', 'minion'], isBossLevel: false, starThresholds: [60, 80, 95] },
      { id: 5, storyIndex: 4, enemies: ['guard', 'guard'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 6, storyIndex: 5, enemies: ['boss'], isBossLevel: true, starThresholds: [50, 70, 90] },
    ],
  },
  // WORLD 2 - Neon District (Grade 6, next 6: indices 6-11)
  {
    id: 2,
    name: 'Neon District',
    description: 'Hack through a cyber city controlled by rogue AI.',
    gradient: 'from-cyan-500 via-blue-600 to-purple-700',
    bgColor: 'bg-cyan-900/20',
    enemyTypes: ['minion', 'guard', 'elite'],
    requiredGradeLevel: 6,
    storyCount: 6,
    unlockRequirement: 3,
    lore: 'The Syndicate\'s tech division operates from the Neon District — a sprawling cyber city where every screen is a surveillance node. The Architect, a genius hacker, controls the digital infrastructure. Shut down the network.',
    levels: [
      { id: 1, storyIndex: 6, enemies: ['minion'], isBossLevel: false, starThresholds: [60, 80, 95] },
      { id: 2, storyIndex: 7, enemies: ['guard'], isBossLevel: false, starThresholds: [60, 80, 95] },
      { id: 3, storyIndex: 8, enemies: ['minion', 'guard'], isBossLevel: false, starThresholds: [60, 80, 95] },
      { id: 4, storyIndex: 9, enemies: ['elite'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 5, storyIndex: 10, enemies: ['guard', 'elite'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 6, storyIndex: 11, enemies: ['boss'], isBossLevel: true, starThresholds: [50, 70, 90] },
    ],
  },
  // WORLD 3 - The Embassy (Grade 7, first 6: indices 12-17)
  {
    id: 3,
    name: 'The Embassy',
    description: 'Navigate diplomatic espionage in a hostile nation.',
    gradient: 'from-amber-600 via-yellow-700 to-orange-800',
    bgColor: 'bg-amber-900/20',
    enemyTypes: ['guard', 'elite'],
    requiredGradeLevel: 7,
    storyCount: 6,
    unlockRequirement: 6,
    lore: 'The Syndicate has placed a mole inside a foreign embassy. Diplomatic tensions are rising. You must identify the Double Agent before classified intelligence falls into enemy hands. Trust no one.',
    levels: [
      { id: 1, storyIndex: 12, enemies: ['guard'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 2, storyIndex: 13, enemies: ['guard', 'guard'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 3, storyIndex: 14, enemies: ['elite'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 4, storyIndex: 15, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 5, storyIndex: 16, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 6, storyIndex: 17, enemies: ['boss'], isBossLevel: true, starThresholds: [45, 65, 85] },
    ],
  },
  // WORLD 4 - Syndicate HQ (Grade 7, next 6: indices 18-23)
  {
    id: 4,
    name: 'Syndicate HQ',
    description: 'The final mission. Take down The Director.',
    gradient: 'from-red-600 via-rose-700 to-red-900',
    bgColor: 'bg-red-900/20',
    enemyTypes: ['guard', 'elite', 'boss'],
    requiredGradeLevel: 7,
    storyCount: 6,
    unlockRequirement: 10,
    lore: 'You\'ve traced the Syndicate back to their fortress headquarters. The Director — the mastermind behind it all — waits inside. Complete your reading objectives, defeat the Director, and dismantle the Syndicate.',
    levels: [
      { id: 1, storyIndex: 18, enemies: ['guard', 'guard'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 2, storyIndex: 19, enemies: ['elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 3, storyIndex: 20, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 4, storyIndex: 21, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 5, storyIndex: 22, enemies: ['boss'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 6, storyIndex: 23, enemies: ['boss'], isBossLevel: true, starThresholds: [40, 60, 80] },
    ],
  },
  // WORLD 5 - The Black Site (Grade 8, first 6: indices 24-29)
  {
    id: 5,
    name: 'The Black Site',
    description: 'Infiltrate a classified military research facility.',
    gradient: 'from-emerald-600 via-green-700 to-teal-900',
    bgColor: 'bg-emerald-900/20',
    enemyTypes: ['guard', 'elite'],
    requiredGradeLevel: 8,
    storyCount: 6,
    unlockRequirement: 14,
    lore: 'Deep in the desert, a decommissioned military base hides a terrible secret. The Syndicate has reactivated the facility — codenamed BLACK SITE — to develop experimental weapons. The Warden runs the compound with an iron fist.',
    levels: [
      { id: 1, storyIndex: 24, enemies: ['guard', 'guard'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 2, storyIndex: 25, enemies: ['elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 3, storyIndex: 26, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 4, storyIndex: 27, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 5, storyIndex: 28, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 6, storyIndex: 29, enemies: ['boss'], isBossLevel: true, starThresholds: [40, 60, 80] },
    ],
  },
  // WORLD 6 - Skyfall Station (Grade 8, next 5: indices 30-34)
  {
    id: 6,
    name: 'Skyfall Station',
    description: 'Board a rogue orbital satellite before it deploys.',
    gradient: 'from-indigo-500 via-violet-600 to-purple-800',
    bgColor: 'bg-indigo-900/20',
    enemyTypes: ['guard', 'elite', 'boss'],
    requiredGradeLevel: 8,
    storyCount: 5,
    unlockRequirement: 18,
    lore: 'The Syndicate has seized control of a decommissioned military satellite — Skyfall Station. Commander Voss oversees the operation from low orbit. You must board the station, disable the uplink, and bring Voss to justice.',
    levels: [
      { id: 1, storyIndex: 30, enemies: ['guard', 'elite'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 2, storyIndex: 31, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 3, storyIndex: 32, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 4, storyIndex: 33, enemies: ['boss', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 5, storyIndex: 34, enemies: ['boss'], isBossLevel: true, starThresholds: [40, 60, 80] },
    ],
  },
  // WORLD 7 - The Deep Web (Grade 9, first 7: indices 35-41)
  {
    id: 7,
    name: 'The Deep Web',
    description: 'Hunt a ghost hacker collective in the digital underworld.',
    gradient: 'from-lime-500 via-green-600 to-emerald-800',
    bgColor: 'bg-lime-900/20',
    enemyTypes: ['elite', 'boss'],
    requiredGradeLevel: 9,
    storyCount: 7,
    unlockRequirement: 22,
    lore: 'The Syndicate\'s most elusive division operates entirely online — a hacker collective known as the Phantom Network. Their leader, The Phantom, has never been seen in person. You must navigate the deep web and unmask The Phantom.',
    levels: [
      { id: 1, storyIndex: 35, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 2, storyIndex: 36, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 3, storyIndex: 37, enemies: ['boss', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 4, storyIndex: 38, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 5, storyIndex: 39, enemies: ['boss', 'elite'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 6, storyIndex: 40, enemies: ['boss', 'boss'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 7, storyIndex: 41, enemies: ['boss'], isBossLevel: true, starThresholds: [35, 55, 75] },
    ],
  },
  // WORLD 8 - Operation Endgame (Grade 9, next 8: indices 42-49)
  {
    id: 8,
    name: 'Operation Endgame',
    description: 'The final arc — stop a global crisis.',
    gradient: 'from-rose-500 via-pink-600 to-fuchsia-800',
    bgColor: 'bg-rose-900/20',
    enemyTypes: ['elite', 'boss', 'boss'],
    requiredGradeLevel: 9,
    storyCount: 8,
    unlockRequirement: 28,
    lore: 'The Syndicate\'s ultimate plan is in motion — Operation Endgame. The Overseer intends to destabilize the global economy and reshape the world order. Every skill you\'ve developed has led to this moment. End this.',
    levels: [
      { id: 1, storyIndex: 42, enemies: ['boss', 'elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 2, storyIndex: 43, enemies: ['boss', 'boss'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 3, storyIndex: 44, enemies: ['boss', 'elite', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 4, storyIndex: 45, enemies: ['boss', 'boss'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 5, storyIndex: 46, enemies: ['boss', 'elite', 'elite'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 6, storyIndex: 47, enemies: ['boss', 'boss', 'elite'], isBossLevel: false, starThresholds: [35, 55, 70] },
      { id: 7, storyIndex: 48, enemies: ['boss'], isBossLevel: false, starThresholds: [35, 55, 70] },
      { id: 8, storyIndex: 49, enemies: ['boss'], isBossLevel: true, starThresholds: [30, 50, 70] },
    ],
  },
  // WORLD 9 - The Vault (Grade 10, first 8: indices 68-75)
  {
    id: 9,
    name: 'The Vault',
    description: 'Break into a fortified underground bunker hiding stolen secrets.',
    gradient: 'from-yellow-700 via-amber-800 to-stone-900',
    bgColor: 'bg-amber-900/20',
    enemyTypes: ['guard', 'elite', 'boss'],
    requiredGradeLevel: 10,
    storyCount: 8,
    unlockRequirement: 34,
    lore: 'Deep beneath the financial district lies The Vault — a fortified bunker where the Syndicate stores stolen government secrets, black market assets, and compromised intelligence. The Vault Keeper, a former military commander, guards the facility with an army of sentinels and automated drones.',
    levels: [
      { id: 1, storyIndex: 68, enemies: ['guard'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 2, storyIndex: 69, enemies: ['guard', 'guard'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 3, storyIndex: 70, enemies: ['elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 4, storyIndex: 71, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 5, storyIndex: 72, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 6, storyIndex: 73, enemies: ['boss', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 7, storyIndex: 74, enemies: ['boss', 'elite'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 8, storyIndex: 75, enemies: ['boss'], isBossLevel: true, starThresholds: [35, 55, 75] },
    ],
  },
  // WORLD 10 - Shadow Protocol (Grade 10, next 8: indices 76-83)
  {
    id: 10,
    name: 'Shadow Protocol',
    description: 'Infiltrate a black-ops program operating in total darkness.',
    gradient: 'from-slate-800 via-gray-900 to-black',
    bgColor: 'bg-slate-900/20',
    enemyTypes: ['guard', 'elite', 'boss'],
    requiredGradeLevel: 10,
    storyCount: 8,
    unlockRequirement: 40,
    lore: 'Shadow Protocol is the Syndicate\'s most classified operation — a covert program that trains sleeper agents and deploys them into governments worldwide. The Shadow Broker controls the entire network from an untraceable location. Your mission: find the Broker and shut down Shadow Protocol permanently.',
    levels: [
      { id: 1, storyIndex: 76, enemies: ['guard', 'guard'], isBossLevel: false, starThresholds: [55, 75, 90] },
      { id: 2, storyIndex: 77, enemies: ['elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 3, storyIndex: 78, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 4, storyIndex: 79, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 5, storyIndex: 80, enemies: ['boss', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 6, storyIndex: 81, enemies: ['boss', 'elite'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 7, storyIndex: 82, enemies: ['boss', 'boss'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 8, storyIndex: 83, enemies: ['boss'], isBossLevel: true, starThresholds: [35, 55, 75] },
    ],
  },
  // WORLD 11 - Arctic Outpost (Grade 11, first 7: indices 111-117)
  {
    id: 11,
    name: 'Arctic Outpost',
    description: 'Survive a frozen research station hiding a deadly weapon.',
    gradient: 'from-blue-300 via-cyan-500 to-blue-800',
    bgColor: 'bg-blue-900/20',
    enemyTypes: ['guard', 'elite', 'boss'],
    requiredGradeLevel: 11,
    storyCount: 7,
    unlockRequirement: 46,
    lore: 'In the frozen wastes of the Arctic, the Syndicate has established an outpost disguised as a climate research station. Known only as Frostbite, the station commander is developing a weapon capable of disrupting global communications. Brave the cold, infiltrate the outpost, and neutralize the threat.',
    levels: [
      { id: 1, storyIndex: 111, enemies: ['guard', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 2, storyIndex: 112, enemies: ['elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 3, storyIndex: 113, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 4, storyIndex: 114, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 5, storyIndex: 115, enemies: ['boss', 'guard'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 6, storyIndex: 116, enemies: ['boss', 'elite'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 7, storyIndex: 117, enemies: ['boss'], isBossLevel: true, starThresholds: [35, 55, 75] },
    ],
  },
  // WORLD 12 - The Labyrinth (Grade 11, next 6: indices 118-123)
  {
    id: 12,
    name: 'The Labyrinth',
    description: 'Navigate an underground maze of tunnels and traps.',
    gradient: 'from-stone-600 via-amber-700 to-stone-800',
    bgColor: 'bg-stone-900/20',
    enemyTypes: ['guard', 'elite', 'boss'],
    requiredGradeLevel: 11,
    storyCount: 6,
    unlockRequirement: 52,
    lore: 'Beneath an ancient city lies The Labyrinth — a network of tunnels and catacombs repurposed by the Syndicate as an impenetrable smuggling route. The Minotaur, a legendary enforcer, patrols the maze. Find the exit, or become another lost soul.',
    levels: [
      { id: 1, storyIndex: 118, enemies: ['guard', 'elite'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 2, storyIndex: 119, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 3, storyIndex: 120, enemies: ['boss', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 4, storyIndex: 121, enemies: ['boss', 'elite'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 5, storyIndex: 122, enemies: ['boss', 'boss'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 6, storyIndex: 123, enemies: ['boss'], isBossLevel: true, starThresholds: [35, 55, 75] },
    ],
  },
  // WORLD 13 - Project Zero (Grade 12, first 9: indices 124-132)
  {
    id: 13,
    name: 'Project Zero',
    description: 'Shut down a rogue bioweapons laboratory.',
    gradient: 'from-green-400 via-emerald-600 to-teal-800',
    bgColor: 'bg-emerald-900/20',
    enemyTypes: ['guard', 'elite', 'boss'],
    requiredGradeLevel: 12,
    storyCount: 9,
    unlockRequirement: 56,
    lore: 'Project Zero is the Syndicate\'s most dangerous undertaking — a hidden laboratory developing biological agents capable of catastrophic destruction. The Catalyst, a brilliant but twisted scientist, oversees the research. You must infiltrate the lab, secure the samples, and bring The Catalyst to justice.',
    levels: [
      { id: 1, storyIndex: 124, enemies: ['guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 2, storyIndex: 125, enemies: ['guard', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 3, storyIndex: 126, enemies: ['elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 4, storyIndex: 127, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 5, storyIndex: 128, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 6, storyIndex: 129, enemies: ['boss', 'guard'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 7, storyIndex: 130, enemies: ['boss', 'elite'], isBossLevel: false, starThresholds: [35, 55, 70] },
      { id: 8, storyIndex: 131, enemies: ['boss', 'boss'], isBossLevel: false, starThresholds: [35, 55, 70] },
      { id: 9, storyIndex: 132, enemies: ['boss'], isBossLevel: true, starThresholds: [30, 50, 70] },
    ],
  },
  // WORLD 14 - Omega Directive (Grade 12, next 12: indices 133-144)
  {
    id: 14,
    name: 'Omega Directive',
    description: 'The ultimate mission — confront the Omega.',
    gradient: 'from-red-400 via-orange-500 to-yellow-600',
    bgColor: 'bg-red-900/20',
    enemyTypes: ['elite', 'boss'],
    requiredGradeLevel: 12,
    storyCount: 12,
    unlockRequirement: 62,
    lore: 'The Omega Directive is the Syndicate\'s endgame — a plan to seize control of global intelligence networks and install The Omega as the unseen ruler of the information age. This is the final mission. Every agent, every skill, every lesson has led here. There is no backup. There is no second chance. Stop The Omega.',
    levels: [
      { id: 1, storyIndex: 133, enemies: ['elite', 'guard'], isBossLevel: false, starThresholds: [50, 70, 85] },
      { id: 2, storyIndex: 134, enemies: ['elite', 'elite'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 3, storyIndex: 135, enemies: ['boss', 'guard'], isBossLevel: false, starThresholds: [45, 65, 80] },
      { id: 4, storyIndex: 136, enemies: ['boss', 'elite'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 5, storyIndex: 137, enemies: ['boss', 'boss'], isBossLevel: false, starThresholds: [40, 60, 75] },
      { id: 6, storyIndex: 138, enemies: ['boss', 'elite', 'guard'], isBossLevel: false, starThresholds: [35, 55, 70] },
      { id: 7, storyIndex: 139, enemies: ['boss', 'boss'], isBossLevel: false, starThresholds: [35, 55, 70] },
      { id: 8, storyIndex: 140, enemies: ['boss', 'elite', 'elite'], isBossLevel: false, starThresholds: [35, 55, 70] },
      { id: 9, storyIndex: 141, enemies: ['boss', 'boss', 'elite'], isBossLevel: false, starThresholds: [30, 50, 65] },
      { id: 10, storyIndex: 142, enemies: ['boss', 'boss', 'boss'], isBossLevel: false, starThresholds: [30, 50, 65] },
      { id: 11, storyIndex: 143, enemies: ['boss'], isBossLevel: false, starThresholds: [30, 50, 65] },
      { id: 12, storyIndex: 144, enemies: ['boss'], isBossLevel: true, starThresholds: [25, 45, 65] },
    ],
  },
];
