import { getStoredTheme } from './gameTheme';

export interface MinigameThemeConfig {
  title: string;
  emoji: string;
  subtitle?: string;
  bgGradient: string;
  accentGradient: string;
  accentColor: string;
  textColor: string;
  successMsg: string;
  failMsg: string;
}

const themes: Record<string, { classic: MinigameThemeConfig; agent: MinigameThemeConfig }> = {
  wordShield: {
    classic: {
      title: 'BUILD YOUR SHIELD!',
      emoji: '🛡️',
      bgGradient: 'from-blue-950/90 via-indigo-900/80 to-slate-900/90',
      accentGradient: 'from-blue-600 via-cyan-500 to-blue-600',
      accentColor: 'border-cyan-300',
      textColor: 'text-cyan-300',
      successMsg: '✨ PERFECT SHIELD! ✨',
      failMsg: '💥 Shield Cracked!',
    },
    agent: {
      title: 'ACTIVATE FIREWALL!',
      emoji: '🔒',
      bgGradient: 'from-slate-950/90 via-gray-900/80 to-slate-900/90',
      accentGradient: 'from-cyan-600 via-teal-500 to-cyan-600',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-400',
      successMsg: '🔒 FIREWALL SECURED!',
      failMsg: '💥 Firewall Breached!',
    },
  },
  spellCombo: {
    classic: {
      title: 'SPELL COMBO',
      emoji: '✨',
      bgGradient: 'from-purple-950/90 via-indigo-900/85 to-violet-900/90',
      accentGradient: 'from-purple-600 via-pink-500 to-purple-600',
      accentColor: 'border-yellow-400',
      textColor: 'text-yellow-400',
      successMsg: 'COMBO COMPLETE!',
      failMsg: 'COMBO BROKEN',
    },
    agent: {
      title: 'HACK SEQUENCE',
      emoji: '💻',
      bgGradient: 'from-gray-950/90 via-slate-900/85 to-gray-900/90',
      accentGradient: 'from-emerald-600 via-green-500 to-emerald-600',
      accentColor: 'border-emerald-400',
      textColor: 'text-emerald-400',
      successMsg: 'SYSTEM BREACHED!',
      failMsg: 'SEQUENCE FAILED',
    },
  },
  dodgeWords: {
    classic: {
      title: 'DODGE & SPEAK',
      emoji: '⚔️',
      bgGradient: 'from-indigo-950/80 via-slate-900/70 to-indigo-900/60',
      accentGradient: 'from-indigo-600 via-blue-500 to-indigo-600',
      accentColor: 'border-blue-400',
      textColor: 'text-blue-300',
      successMsg: '✓ HIT!',
      failMsg: '✗ MISS!',
    },
    agent: {
      title: 'EVADE SURVEILLANCE',
      emoji: '🎯',
      bgGradient: 'from-red-950/80 via-slate-900/70 to-red-900/60',
      accentGradient: 'from-red-600 via-orange-500 to-red-600',
      accentColor: 'border-red-400',
      textColor: 'text-red-300',
      successMsg: '✓ TARGET NEUTRALIZED!',
      failMsg: '✗ DETECTED!',
    },
  },
  rhymeChain: {
    classic: {
      title: 'RHYME CHAIN!',
      emoji: '🎵',
      bgGradient: 'from-purple-900/95 via-pink-900/95 to-purple-900/95',
      accentGradient: 'from-pink-400 to-purple-400',
      accentColor: 'border-pink-400',
      textColor: 'text-pink-300',
      successMsg: '✓ RHYME!',
      failMsg: '✗ TRY AGAIN!',
    },
    agent: {
      title: 'CODE PATTERN!',
      emoji: '🔗',
      bgGradient: 'from-slate-900/95 via-cyan-900/95 to-slate-900/95',
      accentGradient: 'from-cyan-400 to-teal-400',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-300',
      successMsg: '✓ PATTERN MATCH!',
      failMsg: '✗ MISMATCH!',
    },
  },
  speedTypist: {
    classic: {
      title: 'SPEED READING BLITZ!',
      emoji: '⚡',
      bgGradient: 'from-orange-900/95 via-red-900/95 to-yellow-900/95',
      accentGradient: 'from-yellow-400 to-orange-400',
      accentColor: 'border-orange-400',
      textColor: 'text-yellow-300',
      successMsg: 'BLITZ COMPLETE!',
      failMsg: 'TIME UP!',
    },
    agent: {
      title: 'RAPID DECODE!',
      emoji: '📡',
      bgGradient: 'from-slate-900/95 via-amber-900/95 to-slate-900/95',
      accentGradient: 'from-amber-400 to-cyan-400',
      accentColor: 'border-amber-400',
      textColor: 'text-amber-300',
      successMsg: 'DECODE COMPLETE!',
      failMsg: 'SIGNAL LOST!',
    },
  },
  fireballDefense: {
    classic: {
      title: 'FIREBALL ASSAULT!',
      emoji: '🔥',
      bgGradient: 'from-orange-950 via-red-900 to-yellow-900',
      accentGradient: 'from-orange-600 via-red-500 to-orange-600',
      accentColor: 'border-red-400',
      textColor: 'text-red-300',
      successMsg: '🛡️ DEFENSE SUCCESS!',
      failMsg: '🔥 OVERWHELMED!',
    },
    agent: {
      title: 'INCOMING MISSILES!',
      emoji: '🚀',
      bgGradient: 'from-slate-950 via-gray-900 to-slate-950',
      accentGradient: 'from-cyan-600 via-slate-500 to-cyan-600',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-300',
      successMsg: '🎯 MISSILES INTERCEPTED!',
      failMsg: '💥 DEFENSES BREACHED!',
    },
  },
  beastSwarm: {
    classic: {
      title: 'BEAST SWARM!',
      emoji: '🦇',
      bgGradient: 'from-purple-900/80 via-indigo-900/70 to-slate-900/80',
      accentGradient: 'from-purple-600 via-indigo-600 to-purple-600',
      accentColor: 'border-purple-400',
      textColor: 'text-purple-300',
      successMsg: 'SWARM DEFEATED!',
      failMsg: 'OVERWHELMED!',
    },
    agent: {
      title: 'DRONE SWARM!',
      emoji: '📡',
      bgGradient: 'from-slate-900/90 via-gray-900/80 to-slate-900/90',
      accentGradient: 'from-slate-700 via-gray-700 to-slate-700',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-300',
      successMsg: 'DRONES ELIMINATED!',
      failMsg: 'SWARM BREACH!',
    },
  },
  asteroidBarrage: {
    classic: {
      title: 'ASTEROID BARRAGE!',
      emoji: '☄️',
      bgGradient: 'from-purple-950/90 via-slate-900/95 to-slate-950/90',
      accentGradient: 'from-purple-600 to-indigo-600',
      accentColor: 'border-purple-400',
      textColor: 'text-purple-300',
      successMsg: 'ASTEROIDS CLEARED!',
      failMsg: 'IMPACT!',
    },
    agent: {
      title: 'DATA BREACH!',
      emoji: '💾',
      bgGradient: 'from-slate-950/90 via-cyan-900/95 to-slate-950/90',
      accentGradient: 'from-cyan-600 to-teal-600',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-300',
      successMsg: 'PACKETS INTERCEPTED!',
      failMsg: 'BREACH DETECTED!',
    },
  },
  groundRipple: {
    classic: {
      title: 'GROUND RIPPLE!',
      emoji: '🌍',
      bgGradient: 'from-amber-900 via-stone-800 to-stone-950',
      accentGradient: 'from-amber-600 via-stone-500 to-amber-600',
      accentColor: 'border-amber-400',
      textColor: 'text-amber-400',
      successMsg: 'RIPPLE BLOCKED!',
      failMsg: 'GROUND SHATTER!',
    },
    agent: {
      title: 'SHOCKWAVE!',
      emoji: '📳',
      bgGradient: 'from-slate-900 via-gray-800 to-slate-950',
      accentGradient: 'from-cyan-600 via-slate-500 to-cyan-600',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-400',
      successMsg: 'SHOCKWAVE ABSORBED!',
      failMsg: 'SYSTEM OVERLOAD!',
    },
  },
  ghostlyWhispers: {
    classic: {
      title: 'GHOSTLY WHISPERS!',
      emoji: '👻',
      subtitle: 'Speak before they fade!',
      bgGradient: 'from-purple-950/80 via-slate-900/70 to-purple-900/60',
      accentGradient: 'from-purple-400 to-pink-500',
      accentColor: 'border-purple-400',
      textColor: 'text-purple-300',
      successMsg: 'SPIRITS BANISHED!',
      failMsg: 'CONSUMED BY SHADOWS!',
    },
    agent: {
      title: 'INTERCEPTED COMMS!',
      emoji: '📻',
      subtitle: 'Decode before signal fades!',
      bgGradient: 'from-slate-950/80 via-gray-900/70 to-slate-900/60',
      accentGradient: 'from-cyan-400 to-emerald-500',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-300',
      successMsg: 'COMMS DECODED!',
      failMsg: 'SIGNAL LOST!',
    },
  },
  iceCrystalBarrage: {
    classic: {
      title: 'ICE CRYSTAL BARRAGE',
      emoji: '❄️',
      bgGradient: 'from-cyan-900/60 via-blue-900/40 to-transparent',
      accentGradient: 'from-cyan-600 via-blue-500 to-cyan-600',
      accentColor: 'border-cyan-300',
      textColor: 'text-cyan-300',
      successMsg: 'CRYSTALS SHATTERED!',
      failMsg: 'FROZEN SOLID!',
    },
    agent: {
      title: 'EMP BURST',
      emoji: '⚡',
      bgGradient: 'from-slate-900/60 via-blue-950/40 to-transparent',
      accentGradient: 'from-blue-600 via-cyan-500 to-blue-600',
      accentColor: 'border-blue-400',
      textColor: 'text-blue-300',
      successMsg: 'EMP NEUTRALIZED!',
      failMsg: 'SYSTEMS FRIED!',
    },
  },
  rollingBoulders: {
    classic: {
      title: 'ROLLING BOULDERS!',
      emoji: '🪨',
      bgGradient: 'from-amber-900 via-stone-800 to-stone-950',
      accentGradient: 'from-amber-600 to-stone-600',
      accentColor: 'border-amber-400',
      textColor: 'text-amber-300',
      successMsg: 'BOULDERS SMASHED!',
      failMsg: 'CRUSHED!',
    },
    agent: {
      title: 'INCOMING ORDNANCE!',
      emoji: '💣',
      bgGradient: 'from-slate-900 via-gray-800 to-slate-950',
      accentGradient: 'from-red-600 to-gray-600',
      accentColor: 'border-red-400',
      textColor: 'text-red-300',
      successMsg: 'ORDNANCE DEFUSED!',
      failMsg: 'DIRECT HIT!',
    },
  },
  voidPull: {
    classic: {
      title: 'VOID PULL!',
      emoji: '🌀',
      bgGradient: 'from-purple-950/90 via-slate-900/80 to-purple-900/90',
      accentGradient: 'from-purple-600 via-violet-500 to-purple-600',
      accentColor: 'border-purple-400',
      textColor: 'text-purple-300',
      successMsg: 'WORDS RESCUED!',
      failMsg: 'CONSUMED BY VOID!',
    },
    agent: {
      title: 'GRAVITY TRAP!',
      emoji: '🕳️',
      bgGradient: 'from-slate-950/90 via-cyan-900/80 to-slate-900/90',
      accentGradient: 'from-cyan-600 via-teal-500 to-cyan-600',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-300',
      successMsg: 'DATA RECOVERED!',
      failMsg: 'TRAPPED IN FIELD!',
    },
  },
  crystalPrison: {
    classic: {
      title: 'CRYSTAL PRISON!',
      emoji: '💎',
      bgGradient: 'from-cyan-900/90 via-blue-900/80 to-slate-900/90',
      accentGradient: 'from-cyan-600 via-blue-500 to-cyan-600',
      accentColor: 'border-cyan-300',
      textColor: 'text-cyan-300',
      successMsg: 'WORDS FREED!',
      failMsg: 'STILL FROZEN!',
    },
    agent: {
      title: 'CONTAINMENT FIELD!',
      emoji: '🔋',
      bgGradient: 'from-slate-900/90 via-emerald-900/80 to-slate-900/90',
      accentGradient: 'from-emerald-600 via-green-500 to-emerald-600',
      accentColor: 'border-emerald-400',
      textColor: 'text-emerald-300',
      successMsg: 'FIELD DISABLED!',
      failMsg: 'CONTAINMENT HOLDS!',
    },
  },
  wordBarrage: {
    classic: {
      title: 'WORD BARRAGE!',
      emoji: '⚔️',
      bgGradient: 'from-indigo-900/90 via-slate-900/80 to-indigo-900/90',
      accentGradient: 'from-indigo-600 via-blue-500 to-indigo-600',
      accentColor: 'border-blue-400',
      textColor: 'text-blue-300',
      successMsg: 'BARRAGE BLOCKED!',
      failMsg: 'OVERWHELMED!',
    },
    agent: {
      title: 'INTEL BARRAGE!',
      emoji: '📊',
      bgGradient: 'from-slate-900/90 via-cyan-900/80 to-slate-900/90',
      accentGradient: 'from-cyan-600 via-teal-500 to-cyan-600',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-300',
      successMsg: 'INTEL SECURED!',
      failMsg: 'DATA CORRUPTED!',
    },
  },
  vocabShield: {
    classic: {
      title: 'WORD SHIELD!',
      emoji: '🛡️',
      bgGradient: 'from-red-900/90 via-slate-900/80 to-red-900/90',
      accentGradient: 'from-red-600 via-orange-500 to-red-600',
      accentColor: 'border-red-400',
      textColor: 'text-red-300',
      successMsg: '🛡️ SHIELD HOLDS!',
      failMsg: '💥 SHIELD BROKEN!',
    },
    agent: {
      title: 'ENCRYPTION LOCK!',
      emoji: '🔐',
      bgGradient: 'from-slate-900/90 via-cyan-900/80 to-slate-900/90',
      accentGradient: 'from-cyan-600 via-blue-500 to-cyan-600',
      accentColor: 'border-cyan-400',
      textColor: 'text-cyan-300',
      successMsg: '🔐 ENCRYPTED!',
      failMsg: '💥 DECRYPTED!',
    },
  },
  wordEcho: {
    classic: {
      title: 'WORD ECHO!',
      emoji: '🔊',
      bgGradient: 'from-indigo-900/90 via-purple-900/80 to-indigo-900/90',
      accentGradient: 'from-indigo-600 via-purple-500 to-indigo-600',
      accentColor: 'border-indigo-400',
      textColor: 'text-indigo-300',
      successMsg: 'ECHOES COMPLETE!',
      failMsg: 'ECHOES FADED!',
    },
    agent: {
      title: 'SIGNAL BOUNCE!',
      emoji: '📶',
      bgGradient: 'from-slate-900/90 via-emerald-900/80 to-slate-900/90',
      accentGradient: 'from-emerald-600 via-cyan-500 to-emerald-600',
      accentColor: 'border-emerald-400',
      textColor: 'text-emerald-300',
      successMsg: 'SIGNAL LOCKED!',
      failMsg: 'SIGNAL DROPPED!',
    },
  },
  windChase: {
    classic: {
      title: 'WIND CHASE!',
      emoji: '💨',
      bgGradient: 'from-sky-900/90 via-blue-900/80 to-sky-900/90',
      accentGradient: 'from-sky-600 via-blue-500 to-sky-600',
      accentColor: 'border-sky-400',
      textColor: 'text-sky-300',
      successMsg: 'WIND MASTERED!',
      failMsg: 'BLOWN AWAY!',
    },
    agent: {
      title: 'PURSUIT MODE!',
      emoji: '🏃',
      bgGradient: 'from-slate-900/90 via-amber-900/80 to-slate-900/90',
      accentGradient: 'from-amber-600 via-orange-500 to-amber-600',
      accentColor: 'border-amber-400',
      textColor: 'text-amber-300',
      successMsg: 'TARGET ACQUIRED!',
      failMsg: 'TARGET ESCAPED!',
    },
  },
  inkSplash: {
    classic: {
      title: 'INK SPLASH!',
      emoji: '🐙',
      bgGradient: 'from-blue-900/90 via-indigo-900/80 to-blue-900/90',
      accentGradient: 'from-blue-600 via-indigo-500 to-blue-600',
      accentColor: 'border-blue-400',
      textColor: 'text-blue-300',
      successMsg: 'INK CLEARED!',
      failMsg: 'SUBMERGED!',
    },
    agent: {
      title: 'REDACTED FILES!',
      emoji: '📁',
      bgGradient: 'from-slate-900/90 via-red-900/80 to-slate-900/90',
      accentGradient: 'from-red-600 via-rose-500 to-red-600',
      accentColor: 'border-red-400',
      textColor: 'text-red-300',
      successMsg: 'FILES DECLASSIFIED!',
      failMsg: 'ACCESS DENIED!',
    },
  },
  lightningStorm: {
    classic: {
      title: 'LIGHTNING STORM!',
      emoji: '⚡',
      bgGradient: 'from-yellow-900/90 via-slate-900/80 to-yellow-900/90',
      accentGradient: 'from-yellow-600 via-amber-500 to-yellow-600',
      accentColor: 'border-yellow-400',
      textColor: 'text-yellow-300',
      successMsg: 'STORM WEATHERED!',
      failMsg: 'STRUCK DOWN!',
    },
    agent: {
      title: 'POWER SURGE!',
      emoji: '🔌',
      bgGradient: 'from-slate-900/90 via-blue-900/80 to-slate-900/90',
      accentGradient: 'from-blue-600 via-cyan-500 to-blue-600',
      accentColor: 'border-blue-400',
      textColor: 'text-blue-300',
      successMsg: 'GRID STABILIZED!',
      failMsg: 'GRID OVERLOAD!',
    },
  },
  webTrap: {
    classic: {
      title: 'WEB TRAP!',
      emoji: '🕸️',
      bgGradient: 'from-purple-900/90 via-slate-900/80 to-purple-900/90',
      accentGradient: 'from-purple-600 via-violet-500 to-purple-600',
      accentColor: 'border-purple-400',
      textColor: 'text-purple-300',
      successMsg: 'WEB ESCAPED!',
      failMsg: 'TRAPPED!',
    },
    agent: {
      title: 'LASER GRID!',
      emoji: '🔴',
      bgGradient: 'from-slate-900/90 via-red-900/80 to-slate-900/90',
      accentGradient: 'from-red-600 via-rose-500 to-red-600',
      accentColor: 'border-red-400',
      textColor: 'text-red-300',
      successMsg: 'GRID BYPASSED!',
      failMsg: 'LASER TRIGGERED!',
    },
  },
};

export const getMinigameTheme = (gameId: string): MinigameThemeConfig => {
  const storedTheme = getStoredTheme();
  const isAgent = storedTheme === 'agent';
  const config = themes[gameId];
  if (!config) {
    // Fallback
    return isAgent
      ? { title: 'MISSION', emoji: '🎯', bgGradient: 'from-slate-900 via-gray-900 to-slate-900', accentGradient: 'from-cyan-600 to-teal-600', accentColor: 'border-cyan-400', textColor: 'text-cyan-300', successMsg: 'MISSION COMPLETE!', failMsg: 'MISSION FAILED!' }
      : { title: 'CHALLENGE', emoji: '⚔️', bgGradient: 'from-indigo-900 via-purple-900 to-indigo-900', accentGradient: 'from-purple-600 to-indigo-600', accentColor: 'border-purple-400', textColor: 'text-purple-300', successMsg: 'VICTORY!', failMsg: 'DEFEATED!' };
  }
  return isAgent ? config.agent : config.classic;
};

export const isAgentMode = (): boolean => getStoredTheme() === 'agent';
