// Word-to-Emoji mapping for educational word learning
// When kids read these words aloud, an emoji pops up to help them connect words to real-world meanings

export const wordEmojiMap: Record<string, string> = {
  // Animals
  dog: '🐕', dogs: '🐕', puppy: '🐶', puppies: '🐶',
  cat: '🐱', cats: '🐱', kitten: '🐱', kittens: '🐱',
  bird: '🐦', birds: '🐦', robin: '🐦',
  fish: '🐟', fishes: '🐟',
  rabbit: '🐰', rabbits: '🐰', bunny: '🐰', bunnies: '🐰',
  bear: '🐻', bears: '🐻',
  lion: '🦁', lions: '🦁',
  tiger: '🐯', tigers: '🐯',
  elephant: '🐘', elephants: '🐘',
  monkey: '🐵', monkeys: '🐵',
  horse: '🐴', horses: '🐴', pony: '🐴', ponies: '🐴',
  cow: '🐄', cows: '🐄',
  pig: '🐷', pigs: '🐷', piggy: '🐷',
  sheep: '🐑',
  duck: '🦆', ducks: '🦆',
  chicken: '🐔', chickens: '🐔', hen: '🐔',
  frog: '🐸', frogs: '🐸',
  turtle: '🐢', turtles: '🐢',
  snake: '🐍', snakes: '🐍',
  butterfly: '🦋', butterflies: '🦋',
  bee: '🐝', bees: '🐝',
  spider: '🕷️', spiders: '🕷️',
  ant: '🐜', ants: '🐜',
  mouse: '🐭', mice: '🐭',
  owl: '🦉', owls: '🦉',
  wolf: '🐺', wolves: '🐺',
  fox: '🦊', foxes: '🦊',
  deer: '🦌',
  dragon: '🐉', dragons: '🐉',
  dinosaur: '🦕', dinosaurs: '🦕',
  whale: '🐋', whales: '🐋',
  dolphin: '🐬', dolphins: '🐬',
  shark: '🦈', sharks: '🦈',
  octopus: '🐙',
  crab: '🦀', crabs: '🦀',
  penguin: '🐧', penguins: '🐧',
  koala: '🐨', koalas: '🐨',
  panda: '🐼', pandas: '🐼',
  unicorn: '🦄', unicorns: '🦄',

  // People & Family
  mom: '👩', mommy: '👩', mother: '👩',
  dad: '👨', daddy: '👨', father: '👨',
  boy: '👦', boys: '👦',
  girl: '👧', girls: '👧',
  baby: '👶', babies: '👶',
  grandma: '👵', grandmother: '👵', granny: '👵',
  grandpa: '👴', grandfather: '👴',
  family: '👨‍👩‍👧‍👦',
  friend: '🧑‍🤝‍🧑', friends: '🧑‍🤝‍🧑',
  teacher: '👩‍🏫', teachers: '👩‍🏫',
  doctor: '👩‍⚕️', doctors: '👨‍⚕️',
  princess: '👸',
  prince: '🤴',
  king: '🤴', kings: '🤴',
  queen: '👸', queens: '👸',
  knight: '⚔️', knights: '⚔️',
  wizard: '🧙', wizards: '🧙',
  fairy: '🧚', fairies: '🧚',

  // Nature
  tree: '🌳', trees: '🌳',
  flower: '🌸', flowers: '🌸', rose: '🌹', roses: '🌹',
  sun: '☀️', sunny: '☀️', sunshine: '☀️',
  moon: '🌙', moons: '🌙',
  star: '⭐', stars: '⭐',
  cloud: '☁️', clouds: '☁️', cloudy: '☁️',
  rain: '🌧️', rainy: '🌧️', raining: '🌧️',
  snow: '❄️', snowy: '❄️', snowing: '❄️', snowflake: '❄️',
  rainbow: '🌈', rainbows: '🌈',
  mountain: '⛰️', mountains: '⛰️',
  ocean: '🌊', sea: '🌊', wave: '🌊', waves: '🌊',
  river: '🏞️', rivers: '🏞️',
  lake: '🏞️', lakes: '🏞️',
  forest: '🌲', forests: '🌲',
  grass: '🌿', leaf: '🍃', leaves: '🍃',
  wind: '💨', windy: '💨',
  thunder: '⚡', lightning: '⚡',
  fire: '🔥', flame: '🔥', flames: '🔥',
  earth: '🌍', world: '🌍',

  // Food
  apple: '🍎', apples: '🍎',
  banana: '🍌', bananas: '🍌',
  orangefruit: '🍊', oranges: '🍊',
  grape: '🍇', grapes: '🍇',
  strawberry: '🍓', strawberries: '🍓',
  watermelon: '🍉',
  cherry: '🍒', cherries: '🍒',
  peach: '🍑', peaches: '🍑',
  lemon: '🍋', lemons: '🍋',
  cake: '🎂', cakes: '🎂',
  pizza: '🍕',
  burger: '🍔', hamburger: '🍔',
  hotdog: '🌭',
  sandwich: '🥪', sandwiches: '🥪',
  bread: '🍞',
  cookie: '🍪', cookies: '🍪',
  candy: '🍬', candies: '🍬',
  chocolate: '🍫',
  ice: '🧊', icecream: '🍦',
  water: '💧',
  milk: '🥛',
  juice: '🧃',
  egg: '🥚', eggs: '🥚',
  cheese: '🧀',
  carrot: '🥕', carrots: '🥕',
  corn: '🌽',
  tomato: '🍅', tomatoes: '🍅',
  potato: '🥔', potatoes: '🥔',
  salad: '🥗',
  soup: '🍜',

  // Actions & Verbs
  run: '🏃', runs: '🏃', running: '🏃', ran: '🏃',
  walk: '🚶', walks: '🚶', walking: '🚶', walked: '🚶',
  jump: '🦘', jumps: '🦘', jumping: '🦘', jumped: '🦘',
  swim: '🏊', swims: '🏊', swimming: '🏊', swam: '🏊',
  fly: '✈️', flies: '✈️', flying: '✈️', flew: '✈️',
  dance: '💃', dances: '💃', dancing: '💃', danced: '💃',
  sing: '🎤', sings: '🎤', singing: '🎤', sang: '🎤',
  read: '📖', reads: '📖', reading: '📖',
  write: '✍️', writes: '✍️', writing: '✍️', wrote: '✍️',
  draw: '🎨', draws: '🎨', drawing: '🎨', drew: '🎨',
  paint: '🖌️', paints: '🖌️', painting: '🖌️', painted: '🖌️',
  eat: '🍽️', eats: '🍽️', eating: '🍽️', ate: '🍽️',
  drink: '🥤', drinks: '🥤', drinking: '🥤', drank: '🥤',
  sleep: '😴', sleeps: '😴', sleeping: '😴', slept: '😴',
  play: '🎮', plays: '🎮', playing: '🎮', played: '🎮',
  laugh: '😄', laughs: '😄', laughing: '😄', laughed: '😄',
  cry: '😢', cries: '😢', crying: '😢', cried: '😢',
  smile: '😊', smiles: '😊', smiling: '😊', smiled: '😊',
  love: '❤️', loves: '❤️', loving: '❤️', loved: '❤️',
  hug: '🤗', hugs: '🤗', hugging: '🤗', hugged: '🤗',
  kiss: '💋', kisses: '💋', kissed: '💋',
  think: '🤔', thinks: '🤔', thinking: '🤔', thought: '💭',
  dream: '💭', dreams: '💭', dreaming: '💭', dreamed: '💭',
  fight: '⚔️', fights: '⚔️', fighting: '⚔️', fought: '⚔️',
  help: '🤝', helps: '🤝', helping: '🤝', helped: '🤝',
  build: '🔨', builds: '🔨', building: '🏗️', built: '🔨',
  cook: '👨‍🍳', cooks: '👨‍🍳', cooking: '👨‍🍳', cooked: '👨‍🍳',
  clean: '🧹', cleans: '🧹', cleaning: '🧹', cleaned: '🧹',

  // Objects & Things
  book: '📚', books: '📚',
  ball: '⚽', balls: '⚽',
  car: '🚗', cars: '🚗',
  truck: '🚚', trucks: '🚚',
  bus: '🚌', buses: '🚌',
  train: '🚂', trains: '🚂',
  plane: '✈️', airplane: '✈️', planes: '✈️',
  boat: '⛵', boats: '⛵', ship: '🚢', ships: '🚢',
  bike: '🚲', bicycle: '🚲', bikes: '🚲',
  house: '🏠', houses: '🏠', home: '🏠', homes: '🏠',
  castle: '🏰', castles: '🏰',
  door: '🚪', doors: '🚪',
  window: '🪟', windows: '🪟',
  bed: '🛏️', beds: '🛏️',
  chair: '🪑', chairs: '🪑',
  table: '🪑', tables: '🪑',
  phone: '📱', telephone: '📞',
  computer: '💻', computers: '💻',
  clock: '🕐', clocks: '🕐', time: '⏰',
  key: '🔑', keys: '🔑',
  heart: '❤️', hearts: '❤️',
  gift: '🎁', gifts: '🎁', present: '🎁', presents: '🎁',
  balloon: '🎈', balloons: '🎈',
  hat: '🎩', hats: '🎩', cap: '🧢',
  shoe: '👟', shoes: '👟', boot: '👢', boots: '👢',
  dress: '👗', shirt: '👕', pants: '👖',
  bag: '👜', bags: '👜', backpack: '🎒',
  umbrella: '☂️', umbrellas: '☂️',
  glasses: '👓',
  crown: '👑', crowns: '👑',
  sword: '⚔️', swords: '⚔️',
  shield: '🛡️', shields: '🛡️',
  magic: '✨', magical: '✨',
  wand: '🪄',
  treasure: '💎', treasures: '💎',
  gold: '🥇',
  money: '💰',
  map: '🗺️', maps: '🗺️',

  // Places
  school: '🏫', schools: '🏫',
  park: '🏞️', parks: '🏞️',
  zoo: '🦁',
  farm: '🌾', farms: '🌾',
  beach: '🏖️', beaches: '🏖️',
  city: '🏙️', cities: '🏙️',
  village: '🏘️',
  garden: '🌻', gardens: '🌻',
  library: '📚',
  hospital: '🏥',
  store: '🏪', shop: '🏪',
  restaurant: '🍽️',

  // Emotions & Feelings
  happy: '😊', happiness: '😊',
  sad: '😢', sadness: '😢',
  angry: '😠', anger: '😠', mad: '😠',
  scared: '😨', afraid: '😨', fear: '😨',
  brave: '💪', courage: '💪',
  kind: '💕', kindness: '💕',
  nice: '😊',
  mean: '😈',
  surprised: '😲', surprise: '😲',
  excited: '🤩', exciting: '🤩',
  tired: '😫', sleepy: '😴',
  hungry: '🍽️',
  thirsty: '🥤',

  // Colors (with colored shapes/hearts)
  red: '❤️',
  blue: '💙',
  green: '💚',
  yellow: '💛',
  purple: '💜',
  pink: '💗',
  orange: '🧡',
  black: '🖤',
  white: '🤍',
  brown: '🤎',

  // Numbers
  one: '1️⃣', two: '2️⃣', three: '3️⃣', four: '4️⃣', five: '5️⃣',
  six: '6️⃣', seven: '7️⃣', eight: '8️⃣', nine: '9️⃣', ten: '🔟',

  // Time & Seasons
  morning: '🌅',
  night: '🌙', nighttime: '🌙',
  day: '☀️', daytime: '☀️',
  spring: '🌸',
  summer: '☀️',
  fall: '🍂', autumn: '🍂',
  winter: '❄️',
  birthday: '🎂',
  christmas: '🎄',
  halloween: '🎃',

  // Sports & Games
  soccer: '⚽', football: '🏈',
  basketball: '🏀',
  baseball: '⚾',
  tennis: '🎾',
  volleyball: '🏐',
  game: '🎮', games: '🎮',
  toy: '🧸', toys: '🧸',
  doll: '🎎', dolls: '🎎',
  puzzle: '🧩', puzzles: '🧩',

  // Music
  music: '🎵', song: '🎵', songs: '🎵',
  guitar: '🎸',
  piano: '🎹',
  drum: '🥁', drums: '🥁',
  trumpet: '🎺',
  violin: '🎻',
};

// Helper function to get emoji for a word (case-insensitive)
export const getWordEmoji = (word: string): string | null => {
  const cleanWord = word.toLowerCase().replace(/[^a-zA-Z]/g, '');
  return wordEmojiMap[cleanWord] || null;
};
