project_id = "sjigkjwkgovculkovcjy"

[functions.start-tournament]
verify_jwt = true

[functions.seed-and-create-matches]
verify_jwt = true

[functions.start-round]
verify_jwt = true

[functions.show-next-question]
verify_jwt = false

[functions.buzz-in]
verify_jwt = true

[functions.submit-answer]
verify_jwt = true

[functions.end-round-and-compute-winners]
verify_jwt = true

[functions.generate-question-ai]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-aura]
verify_jwt = true

[functions.generate-practice-exercises]
verify_jwt = true
